"""AI-generated outreach content model.

Container for the personalized sales assets produced per lead by the AI service
(later phase). Kept purely as data so it can be generated by any LLM provider
and serialized into the CRM / exports unchanged.
"""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator


class AIContent(BaseModel):
    """All personalized outreach copy for a single lead."""

    whatsapp_message: str = ""
    email: str = ""
    cold_call_script: str = ""
    follow_ups: list[str] = Field(
        default_factory=list,
        description="Sequenced follow-up messages (typically 3).",
    )
    objection_handling: str = ""
    portfolio_response: str = ""
    timeline_response: str = ""
    why_choose_us: str = ""

    @field_validator("follow_ups")
    @classmethod
    def _cap_follow_ups(cls, value: list[str]) -> list[str]:
        # Defensive: keep the model tolerant of over-generation.
        return value[:5]

    @property
    def is_populated(self) -> bool:
        """True once the core assets have been generated."""
        return bool(self.whatsapp_message and self.email and self.cold_call_script)
